server:
  port: 9999

# jsp
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  #database
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: system
    password: 1234

#mybatis
mybatis:
  mapper-locations: mapper/**/*.xml
  type-aliases-package: com.example.excel.*

